remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
title: Angely C. Suarez DeJesus
description: Career Portfolio
<h1 style="background-color:rgb(300, 300, 300);">Shades of Grey</h1>

